project:
  type: website

website:
  title: "AI in Cultural Collections"
  site-url: https://murphyqm.github.io/cultural-collections-guidance
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: guidance/index.qmd
        text: Guidance
      - href: tools/index.qmd
        text: Toolkit
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



